### ISSUE TITLE
ogrFeatureToSlot() assumptions

### ISSUE THREAD

**Issue by rouault** [pramsey/pgsql-ogr-fdw#2] opened 2014-12-20 14:04 UTC
ogrFeatureToSlot() assumes that the CREATE FOREIGN TABLE statement used is exactly the one suggested by ogr_fdw_info. If trying something else, PG columns receive content from unexpected OGR fields.

**Comment by pramsey** [comment] 2015-06-18 12:50
Note that there are also column-level OPTIONS available, that are used in `postgres_fdw` to control the column mapping. The question is what a good policy would be?

* if there's a column name OPTION then map using that
* otherwise map consistent name/type combinations together
* otherwise... 
    * ignore?
    * order of declaration?

**Comment by robe2** [comment] 2016-01-05 20:07
I really would go with explicit mapping of remote column to local column or order based on a  basic OGR SQL query syntax very similar to what tds_fdw does - 
https://github.com/GeoffMontee/tds_fdw/blob/master/ForeignTableCreation.md

So perhaps something like layer_query  instead of layer and otherwise an option that has listed column names of remote columns to pull which ends up looking like an ogr select statement anyway.

though can you auto-infer the structure from a query using ogr?  I assume you can.

The reason why I wouldn't try to guess column names and data types, is that could go south really quickly.  For example someone gets a layer with spanish named columns.  They decide,  hey I don't speak spanish -- let me englishify them, and then your model becomes totally screwed.

**Comment by rouault** [comment] 2016-01-05 20:13
> though can you auto-infer the structure from a query using ogr? I assume you can.

A few interesting functions :
- OGR_L_GetLayerDefn: http://gdal.org/ogr__api_8h.html#a7b67ea4ab5892c6720460dc7f66eca2d
- OGR_FD_GetFieldCount & OGR_FD_GetFieldDefn : http://gdal.org/ogr__api_8h.html#a586a14271a457387a2b5c0097a02c8da
- OGR_Fld_GetNameRef 	 : http://gdal.org/ogr__api_8h.html#a8d7640a6b6a47a95d83415f9271ffe30
- OGR_Fld_GetType : http://gdal.org/ogr__api_8h.html#ad8d150dfc678e0a2a7f5241ba38c5611

**Comment by pramsey** [comment] 2016-04-14 19:33
So, in terms of explicit column mapping, it sounds like we would a rule:

* if you supply a `column_name` option for any foreign column, you must supply them for *all* columns
* if you don't supply an explicit mapping, we will map in column order (current behavior)

Yes, robe2?

**Comment by pramsey** [comment] 2016-04-14 20:18
Or, maybe you have to always supply an table column for every column in the OGR layer, but you can use column_name to remap them, thus avoiding the potential ugliness (and collisions) of laundering.

**Comment by pramsey** [comment] 2016-04-18 18:10
OK, this work is **merged**. We now no longer require an FDW table to have all the columns of the source. Columns will be matched from FDW to source based on column name, laundered and unlaundered, with the `column_name` column-level OPTION available to customize the behaviour. So it's actually possible now to have an FDW column named "george" exposing an OGR column named "gracie".

From the regression tests:
```
CREATE FOREIGN TABLE column_name_test (
 fid integer,
 name varchar OPTIONS (column_name '2ame'),
 theage integer OPTIONS (column_name 'age'),
 height real OPTIONS (column_name 'Height'),
 birthdate date OPTIONS (column_name 'b-rthdate')
) SERVER myserver
OPTIONS (layer '2launder');
```

**Closed by pramsey** 2016-04-18 18:10 UTC
Labels: enhancement
