### ISSUE TITLE
MSSQL foreign table does not allow updates

### ISSUE THREAD

**Issue by MikeD-GEOTrac** [pramsey/pgsql-ogr-fdw#171] opened 2019-07-17 17:38 UTC
I've created a MSSQL Spatial table using ogr2ogr (source table is a PostGIS table) and then created a foreign table of that MSSQL spatial table using ogr_fdw.  I can insert and delete using the foreign table, but not update.  Whenever I try an update I get the error 'foreign table "xxxx" does not allow updates'

I can update the MSSQL table with ogrinfo -sql, but when I try the same on the foreign table I get the above error.  If I try with ogrinfo -dialect SQLite -sql I get an error saying 'Unable to update features in tables without a recognised FID column'

When I run ogr_fdw_info -f it shows MSSQLSpatial <read/write>, although it also doesn't list PostgreSQL at all....

Any insight into why updates aren't working would be great.

additional info:  Windows Server 2012, PostgreSQL 11.4, PostGIS 2.5.2, ogr_fdw 1.0.7, GDAL 2.2.4

**Comment by MikeD-GEOTrac** [comment] 2019-07-19 21:03
Here's some steps to try and repeat this

create postgres table
```
CREATE TABLE pgtest (
	gid INT primary key generated by default as identity,
	private bool NULL,
	lanes int4 NULL,
	roadid uuid NOT NULL DEFAULT uuid_generate_v1(),
	primaryname text NULL,
	geom geometry(LINESTRING, 4326) NOT null
	);

insert into pgtest (private, lanes, primaryname, geom) values (true, 1, 'road1', st_geomfromtext('LINESTRING(0 0, 1 1)',4326));
insert into pgtest (private, lanes, primaryname, geom) values (false, 1, 'road2', st_geomfromtext('LINESTRING(2 2, 3 3)',4326));
insert into pgtest (private, lanes, primaryname, geom) values (true, 1, 'road3', st_geomfromtext('LINESTRING(-1 -1, -2 -2)',4326));
insert into pgtest (private, lanes, primaryname, geom) values (true, 1, 'road4', st_geomfromtext('LINESTRING(5 5, 6 6)',4326));
insert into pgtest (private, lanes, primaryname, geom) values (false, 1, 'road5', st_geomfromtext('LINESTRING(-3 -3, -1 -2)',4326));
insert into pgtest (private, lanes, primaryname, geom) values (true, 1, 'road6', st_geomfromtext('LINESTRING(1 2, 3 4)',4326));
```

create mssql table from postgres table
```
ogr2ogr -f MSSQLSpatial "MSSQL:server=xxxx;database=xxx;UID=xxx;PWD=xxx" PG:"host=xxx port=xxx dbname=xxx
user=xxx password=xxx" pgtest -nln mssqltest
```
use ogr_fdw_info to get sql for ogr_fdw server and foreign table
```
ogr_fdw_info -s "MSSQL:server=xxx;database=xxx;UID=xx;PWD=xxx" -l mssqltest
```
output
```
CREATE SERVER myserver
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
        datasource 'MSSQL:server=xxx;database=xxx;UID=xx;PWD=xxx',
        format 'MSSQLSpatial' );

CREATE FOREIGN TABLE ogrfdwtest (
  fid bigint,
  geom Geometry(LineString,4326),
  private real,
  lanes integer,
  roadid varchar,
  primaryname varchar
) SERVER myserver
OPTIONS (layer 'mssqltest');
```
insert a record, works fine
```
insert into ogrfdwtest (roadid, private, lanes, primaryname, geom) values ('test',1, 5, 'road7', st_geomfromtext('LINESTRING(7 8, 9 10)',4326));
```
update a record
```
update ogrfdwtest set lanes = 6 where primaryname='road5'
```
errors with:
```
SQL Error [55000]: ERROR: foreign table "ogrfdwtest" does not allow updates
```

**Comment by robe2** [comment] 2019-08-11 13:54
One thing you can try to debug issue 

```
SET client_min_messages = debug2;
update ogrfdwtest set lanes = 6 where primaryname='road5'
```
and see what notice you get if any.

Can you also add the CREATE TABLE statement for your SQL Server? and I'll test it out.  If it has no primary key defined, I think ogr_fdw might assume it's not updateable.

There was also some changes done in ogrfdw 1.0.8 around this area, so whatever is in 1.0.7 might be resolved in 1.0.8.

You can try out build from here - https://winnie.postgis.net/download/windows/pg11/buildbot/extras/ogrfdw-pg11-binaries-1.0.8w64gcc48.zip

You should only need the ogr_fdw.dll (in lib folder) and related extensions files in share/extensions.

Alternatively you can wait another 1-2 weeks or so when I release PostGIS 2.5.3 bundle

**Comment by pramsey** [comment] 2019-12-02 23:23
Yeah, you really need an integer primary key if you want updateability.

**Comment by robe-app** [comment] 2020-07-21 21:32
I confirmed it works with the MSSpatial driver if your primary key is an integer.  For ODBC driver it never works to update since the fid in that case is a dummy.

This is testing with windows build PostgreSQL 12,  PostGIS 3.0, ogr_fdw 1.0.9, GDAL 2.4.4

So here is my working example:
-- the 2433 is my sql server port - if using standard 1433 you can leave that out
```
CREATE SERVER mssql_spatial
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource 'MSSQL:server=myserver,2433;database=testdb;UID=testuser;PWD=testpassword;Tables=Tables=dbo.ClientDb,dbo.tblTest',
    format 'MSSQLSpatial' );

CREATE SCHEMA ms_test;
IMPORT FOREIGN SCHEMA ogr_all FROM SERVER mssql_spatial INTO ms_test;
---  imports 2 tables --

UPDATE ms_test.tbltest SET col1 = 'Hello' WHERE fid = 1;
SELECT * FROM ms_test.tbltest WHERE fid = 1;  --confirmed my change was saved
```

My SQL Server table structure looks like below - this is a SQL Server 2008 haven't tried on newer but don't expect things to be different.

```
CREATE TABLE [dbo].[tblTest](
	[col1] [char](8000) NULL,
	[col2] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_tblTest] PRIMARY KEY CLUSTERED 
(
	[col2] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```

**Comment by robe2** [comment] 2020-07-21 21:37
I confirmed it works with the MSSpatial driver if your primary key is an integer.  For ODBC driver it never works to update since the fid in that case is a dummy.

This is testing with windows build PostgreSQL 12,  PostGIS 3.0, ogr_fdw 1.0.9, GDAL 2.4.4

So here is my working example:
-- the 2433 is my sql server port - if using standard 1433 you can leave that out
```
CREATE SERVER mssql_spatial
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource 'MSSQL:server=myserver,2433;database=testdb;UID=testuser;PWD=testpassword;Tables=Tables=dbo.ClientDb,dbo.tblTest',
    format 'MSSQLSpatial' );

CREATE SCHEMA ms_test;
IMPORT FOREIGN SCHEMA ogr_all FROM SERVER mssql_spatial INTO ms_test;
---  imports 2 tables --

UPDATE ms_test.tbltest SET col1 = 'Hello' WHERE fid = 1;
SELECT * FROM ms_test.tbltest WHERE fid = 1;  --confirmed my change was saved
```

My SQL Server table structure looks like below - this is a SQL Server 2008 haven't tried on newer but don't expect things to be different.

```
CREATE TABLE [dbo].[tblTest](
	[col1] [char](8000) NULL,
	[col2] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_tblTest] PRIMARY KEY CLUSTERED 
(
	[col2] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```
The postgresql table sadly looses the original structure -- so col2 because fid

as follows:
```
CREATE FOREIGN TABLE ms_test.tbltest(
    fid bigint NULL,
    geom bytea NULL,
    col1 character varying(8000) NULL COLLATE pg_catalog."default"
)
    SERVER ntcmaster_spatial
    OPTIONS (layer 'tblTest');

```
which is why I tend to prefer the ODBC driver if I just need to read and not update

**Comment by robe2** [comment] 2020-07-21 21:47
@pramsey feel free to close this ticket out I think its just a limitation of the need for a primary key fid.

I also tried this test and worked fine - this one is on the other table I brought in that also has a primary key and had a record with clientname = 'Test' and it successfully updated it to Test 2.

Neither of these tables are spatial though but I don't think that matters.

````
UPDATE ms_test.clientdb SET clientname = 'Test 2' WHERE clientname = 'Test';
````

**Comment by robe-app** [comment] 2020-08-01 21:49
FWIW I just tested ogr_fdw (the one distributed by apt.postgresql.org) on a Ubuntu 20.04 with PostgreSQL 12 against a Windows 2008 / SQL Server 2008 using the TDS driver.  The MSSQL2017 I couldn't get to work, but I suspect that's just cause my SQL Server is too old and was probably trying a protocol not supported.

My FreeTDS /etc/odbc.ini looks like
```
[FreeTDS]
Description     = FreeTDS for connecting to Sybase and SQL Server
Driver          = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
```

and my ogr_fdw connection looks like

```
CREATE SERVER mssql_test
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource 'MSSQL:server=myserver,1433;database=mydb;UID=user;PWD=password;driver=FreeTDS;Tables=Clientdb,Table2,Table3', format 'MSSQLSpatial');

IMPORT FOREIGN SCHEMA ogr_all FROM SERVER mssql_test INTO ms_test;
```

I was able to run 

```
UPDATE ms_test.clientdb SET clientname = 'Test 2' WHERE clientname = 'Test';
```

and it worked fine.

**Comment by robe2** [comment] 2020-10-04 02:07
@pramsey  Can you please close this out?  All these open issues that are not issues are bugging me.

I've beaten this problem to death. It does not work with ODBC because OGC ODBC doesn't return primary keys. fid is always a dummy autogenerated.

I concluded it works if you are using MSSpatial driver and a UnixODBC driver that supports it.  I've even made this work on a Centos 6 box running PostgreSQL 9.6 using MSSpatial driver and a SQL Server 14 ODBC driver provided by microsoft against a Unix SQL Server 14. I have also made it work on a PostgreSQL Ubuntu 20.04 server connecting to a Windows SQL Server 2008 using the TDS Driver.

**Closed** 2020-10-04 20:06 UTC
