### ISSUE TITLE
Error creating Server: unable to connect to data source

### ISSUE THREAD

**Issue by jaitor1** [pramsey/pgsql-ogr-fdw#44] opened 2015-12-01 10:45 UTC
Hi,

I execute ogr_fdw_info succesfully:

D:\Program Files\PostgreSQL\9.3\bin> .\ogr_fdw_info.exe -s "ODBC:SQLPROD" -l "dbo.MCOMERC"

OUT:
Warning 1: No column definitions found for table 'dbo.VeladoresA├▒oActual', layer not usable.

CREATE SERVER myserver
  FOREIGN DATA WRAPPER ogr_fdw
  OPTIONS (
    datasource 'ODBC:SQLPROD',
    format 'ODBC' );

CREATE FOREIGN TABLE dbo_mcomerc (
  fid integer,
  codtipoexp varchar,
  a_o integer,
  m_propietario_local varchar )
  SERVER myserver
  OPTIONS ( layer 'dbo.MCOMERC' );

If I execute the CREATE SERVER statement in Postgres I get:

********** Error **********

ERROR: unable to connect to data source "ODBC:SQLPROD"
SQL state: HV00D

My PostgreSQL version: "PostgreSQL 9.3.5, compiled by Visual C++ build 1600, 64-bit"

My PostGIS version: "POSTGIS="2.2.0 r14208" GEOS="3.5.0-CAPI-1.9.0 r4090" PROJ="Rel. 4.9.1, 04 March 2015" GDAL="GDAL 2.0.0, released 2015/06/14" LIBXML="2.7.8" LIBJSON="0.12" RASTER"

OS:  Windows 8.1

Any help or advice would be appreacited..

**Comment by robe2** [comment] 2016-01-01 01:06
@jaitor1 ,

Your issue might be because you didn't specify a user and password for SQL server server.  If you are relying on a trusted connection (which works fine when you are using ogr_fdw_info because it's running under your user account), then your PostgreSQL service would have to run under a network user that is trusted by SQL Server.  Also I think there are issues with it reading passwords from registry for ODBC.

Try doing as I described here: 

http://www.postgresonline.com/journal/archives/355-Connecting-to-SQL-Server-from-Linux-using-FDWs.html

```

ALTER SERVER mssql_tds_test 
    OPTIONS(SET datasource 'ODBC:your_user/your_password@SQLPROD');

```

If the issue is a table causing the problem, you can prevent OGR from scanning all tables by explicitly specifying tables you plan to use.  I usually do this for performance reasons since huge SQL Server databases take a long time otherwise for it to scan the layer list.

```
ALTER SERVER mssql_tds_test 
    OPTIONS(SET datasource 'ODBC:your_user/your_password@SQLPROD,information_schema.columns,dbo.ZIPS,someschema.whatever');

```

**Comment by robe2** [comment] 2016-01-05 17:50
@pramsey  I suspect this is not a bug and just the way the user is trying to connect to SQL Server.  So might just want to close this out as a "worksforme".  I connect to SQL Server all the time and haven't had any issue since the date/datetime thing you fixed a while ago.

**Closed** 2016-01-05 17:52 UTC
